[project]
name = "finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.5",
    "langchain>=0.3.27",
    "langchain-huggingface>=0.3.1",
    "torch>=2.7.1",
    "transformers>=4.54.0",
]
